osscameroon/global-github-actions

.github/workflows/notify_on_pull_request_open.yaml, .github/workflows/recommend_yotas_issues.yaml, .github/workflows/report_contributions.yaml, .github/workflows/report_number_of_yotas.yaml, .github/workflows/report_opencollective.yaml
For some reason the telegram-action is failing , the fix is to not use the master version of the GA.
as described in this comment https://github.com/appleboy/telegram-action/issues/10#issuecomment-829932577
=> feat: change telegram action version

.github/workflows/report_open_projects.yaml, .github/workflows/report_open_projects/get_open_projects.sh
- github action to notify for new open-projects
=> feat(open-project): send available open-projects

.github/workflows/opencollective_contributions/get_opencollective_info.sh, .github/workflows/report_open_projects/get_open_projects.sh
=> typos(x): cleaning stuffs + typos

.github/workflows/report_a_quiz.yaml, .github/workflows/report_quiz/report_quiz.sh
Implemented a Quiz bot that will : 
- fetch for questions
- send a question
- send propositions
=> feat(quiz): implemented a Quiz bot

.github/workflows/report_open_projects.yaml, .github/workflows/report_open_projects/get_open_projects.sh
=> feat: quiz bot

.github/workflows/social_media_message_scheduler.yaml, .github/workflows/social_media_message_scheduler/.example-secret-env, .github/workflows/social_media_message_scheduler/.gitignore, .github/workflows/social_media_message_scheduler/Makefile, .github/workflows/social_media_message_scheduler/main.py, .github/workflows/social_media_message_scheduler/requirements.txt, .github/workflows/social_media_message_scheduler/res/messages.yaml, .github/workflows/social_media_message_scheduler/telegram.py, .github/workflows/social_media_message_scheduler/twitter.py, .gitignore
This pull request implements a GitHub Action that read some predefined messages from a yaml file and send them
to the appropriate social media.
Since we decided to read some messages from a yaml file I would like yo submit a schema for this file `messages.yaml`.
```yaml
- message_name_1:
#the list of target describes where you want your message to be sent it can be 
targets:
- twitter
message: |
Hi all,
You have a project idea you think the Cameroonian community might benefit from ?
You can submit this idea to the osscameroon community and we can work on it together.
Click here to submit Down pointing backhand index 
https://github.com/osscameroon/Open-Projects/issues/new?assignees=&labels=&template=project-idea-template.md&title=
Join us here https://t.me/joinchat/UpKZh_KXTaTx7JD7 …
```
=> feat: add social media message scheduler

.github/workflows/social_media_message_scheduler.yaml, .github/workflows/social_media_message_scheduler/res/messages.yaml, .github/workflows/validate_message_scheduler_messages.yaml
We added a series of messages to be published on twitter
=> Add more messages

.github/workflows/report_quiz/report_quiz.sh
- fix some characters escapes...
=> fix:quiz bot

.github/workflows/report_quiz/report_quiz.sh
- now send 2 messages
- now send the number of options depending of possibilities
=> optim: some optimizations on the quizbot

README.md
=> doc: updated the README

.github/workflows/report_open_projects/get_open_projects.sh
=> fix: fix escapes

.github/workflows/report_quiz/report_quiz.sh
- fix trailing commas surrounding options payload
=> fix: trailing commas surrounding options payload

.github/workflows/notify_on_pull_request_open.yaml
- Send the pull event also inside the telegram group channel
=> pull: send the pull event also into the ossgroup

.github/workflows/social_media_message_scheduler/res/messages.yaml
=> feat: attempt to fix #caparledev hashtag

.github/workflows/social_media_message_scheduler/twitter.py
=> feat: rollback code abstration

.github/workflows/hermes_open_project_recommendation.yaml
We would like the bot `hermes` to send messages to twitter.
Depends on https://github.com/osscameroon/osscameroon-website/pull/246
=> feat(hermes): add twitter secrets

.github/workflows/report_quotes.yaml, .github/workflows/report_quotes/report_quotes.sh, README.md
- added a github action for sending programming quotes
=> feat: report quotes

.github/workflows/report_jobs.yaml, .github/workflows/report_jobs/report_jobs.sh, README.md
- added a report-jobs github action
Using a curl with bash and parsing output comming from from https://documenter.getpostman.com/view/18545278/UVJbJdKh
=> feat: report-jobs github action

.github/workflows/report_quotes/report_quotes.sh
=> fix: quote

.github/workflows/report_quiz/report_quiz.sh
Yet another weird fix to prevent having in the poll options with spaces.
=> fix: fix to prevent having space in the poll options 

.github/workflows/report_jobs/report_jobs.sh
=> fix: report/jobs

.github/workflows/report_quiz/report_quiz.sh
=> fix: problem to escape quotes

.github/workflows/report_quiz/report_quiz.sh
=> fix: all the quiz answers was not take in account

.github/workflows/report_quiz/report_quiz.sh
It's now possible to know the context of the quiz.
Linked to #65
=> feat: quiz context

.github/workflows/report_quiz/report_quiz.sh
In some quiz, we can have many answers.
It's better to be able to make multiple choices in this case.
In waiting of the merging of #72
=> feat: multiple choices

.github/workflows/social_media_message_scheduler/res/messages.yaml
- Fix typos on url for blog posts
=> fix: typos on links of blogs

.github/workflows/social_media_message_scheduler/twitter.py
Properly check before post a new media content on twitter !
=> fix: properly post a new media scheduler

.github/workflows/social_media_message_scheduler/README.md, .github/workflows/social_media_message_scheduler/res/messages.yaml
- add a README.md for the social_media_scheduler
- add social media scheduler
=> add message in french

.github/workflows/notify_on_broken_link_detected.yaml, .github/workflows/notify_on_broken_link_detected/install_deps.sh, .github/workflows/notify_on_broken_link_detected/run.sh
- A GitHub action to check for the broken links and send the report on the osscameroon channel if a broken link is found.
- Linked to the issue #97
=> add broken_link_checker check scheduler

.github/workflows/report_contributions/get_contribution_report.sh
Looks like this now
```console
elhmn              : ▇▇▇▇▇ 390.00
Asam237            : ▇▇ 176.00
Sanix-Darker       : ▇▇ 163.00
FanJups            : ▇ 94.00
pythonbrad         : ▏ 76.00
tericcabrel        : ▏ 74.00
Theryx             : ▏ 62.00
gtindo             : ▏ 58.00
Zaker237           : ▏ 55.00
godsakani          : ▏ 41.00
yokwejuste         : ▏ 37.00
DipandaAser        : ▏ 33.00
PILOTEZEBS         : ▏ 26.00
afranck64          : ▏ 12.00
```
=> sort report contributions

.github/workflows/report_news.yaml
Clean the first n line from an hash file list of news
Our hash file for news is growing fast and we need a cleaver and simple way to clean top n lines from the file !
This is my proposition for that : a simple lines count + tail
=> feat: programmatically clean hashes

.github/workflows/report_jokes.yaml, .github/workflows/report_jokes/main.py, README.md
Same as : https://github.com/osscameroon/global-github-actions/pull/109 
Got reverted here from the main : https://github.com/osscameroon/global-github-actions/pull/112
=> feat: add report-joke (bis)

.github/workflows/report_jobs.yaml, .github/workflows/report_jobs/report_jobs.sh
This job was not working before due to parsing error while formating the output of the request
The most obvious solution i made was to remove the explicit format output of the github action that has the role of formating the message to telegram !
=> fix: report jobs github actions

.github/workflows/report_jobs.yaml
We're disabling this bot for now, too much noise, we may add later a better API to fill it !
=> chore: disable report job github acttion for now

.github/workflows/report_quotes.yaml
- #120 
Migration to python 3.11 instead.
=> fix(report_quotes): problem to install python

.github/workflows/report_news.yaml
This is alternative to https://github.com/osscameroon/global-github-actions/pull/125 and should help us fix https://github.com/osscameroon/global-github-actions/issues/123
@pythonbrad
=> Fix the hash storage
